CREATE TABLE `co_applicants` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` int NOT NULL,
	`firstName` varchar(100),
	`lastName` varchar(100),
	`ssn` varchar(20),
	`dateOfBirth` varchar(20),
	`maritalStatus` enum('single','married','divorced'),
	`cellPhone` varchar(20),
	`workPhone` varchar(20),
	`email` varchar(320),
	`dlState` varchar(2),
	`dlNumber` varchar(50),
	`dlFrontUrl` text,
	`dlBackUrl` text,
	`currentStreet` text,
	`currentCity` varchar(100),
	`currentState` varchar(2),
	`currentZip` varchar(10),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `co_applicants_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `rental_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`status` enum('draft','submitted','approved','rejected','pending','under_review','denied','incomplete') NOT NULL DEFAULT 'draft',
	`propertyAddress` text,
	`firstName` varchar(100),
	`lastName` varchar(100),
	`ssn` varchar(20),
	`dateOfBirth` varchar(20),
	`maritalStatus` enum('single','married','divorced'),
	`cellPhone` varchar(20),
	`workPhone` varchar(20),
	`email` varchar(320),
	`dlState` varchar(2),
	`dlNumber` varchar(50),
	`dlFrontUrl` text,
	`dlBackUrl` text,
	`currentStreet` text,
	`currentCity` varchar(100),
	`currentState` varchar(2),
	`currentZip` varchar(10),
	`reasonForMoving` varchar(100),
	`employerName` text,
	`employerStreet` text,
	`employerCity` varchar(100),
	`employerState` varchar(2),
	`employerZip` varchar(10),
	`position` varchar(100),
	`officePhone` varchar(20),
	`monthlyGrossPay` varchar(50),
	`supervisorName` varchar(200),
	`supervisorPhone` varchar(20),
	`additionalIncome` text,
	`employmentFrom` varchar(20),
	`employmentTo` varchar(20),
	`incomeProofUrls` json,
	`emergencyName` varchar(200),
	`emergencyRelationship` varchar(100),
	`emergencyPhone` varchar(20),
	`emergencyEmail` varchar(320),
	`emergencyAddress` text,
	`emergencyCity` varchar(100),
	`emergencyState` varchar(2),
	`emergencyZip` varchar(10),
	`medicalName` varchar(200),
	`medicalPhone` varchar(20),
	`medicalEmail` varchar(320),
	`medicalAddress` text,
	`medicalCity` varchar(100),
	`medicalZip` varchar(10),
	`beenSued` varchar(3),
	`beenSued_explanation` text,
	`brokenLease` varchar(3),
	`brokenLease_explanation` text,
	`convictedFelony` varchar(3),
	`convictedFelony_explanation` text,
	`moveInAmountAvailable` varchar(3),
	`moveInAmount_explanation` text,
	`filedBankruptcy` varchar(3),
	`filedBankruptcy_explanation` text,
	`bankruptcyDischarged` varchar(3),
	`rentPlanDuration` text,
	`lockedOutBySheriff` varchar(3),
	`lockedOutBySheriff_explanation` text,
	`servedLateRentNote` varchar(3),
	`servedLateRentNote_explanation` text,
	`occupantsSmoke` varchar(3),
	`occupantsSmoke_explanation` text,
	`landlordProblems` varchar(3),
	`landlordProblemsExplanation` text,
	`additionalIncomeSource` text,
	`creditCheckComment` text,
	`petsInfo` text,
	`howHeardAboutHome` text,
	`passwordHash` varchar(100),
	`stripePaymentIntentId` varchar(100),
	`stripeCheckoutSessionId` varchar(100),
	`paymentStatus` enum('unpaid','paid','refunded') DEFAULT 'unpaid',
	`paymentAmount` int,
	`signatureName` varchar(200),
	`signatureDrawUrl` text,
	`signatureDate` varchar(30),
	`currentStep` int DEFAULT 1,
	`resumeToken` varchar(64),
	`resumeTokenExpiresAt` timestamp,
	`reminderSentAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`submittedAt` timestamp,
	CONSTRAINT `rental_applications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `vehicles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`applicationId` int NOT NULL,
	`make` varchar(100),
	`model` varchar(100),
	`color` varchar(50),
	`year` varchar(4),
	`licensePlate` varchar(20),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `vehicles_id` PRIMARY KEY(`id`)
);
